<?php
$this->headTitle('Add a Tutorial');
$this->headScript()->prependFile('/js/jquery.tagsinput.min.js');
$this->headLink()->appendStylesheet('/css/jquery.tagsinput.css');
$this->headScript()->captureStart();
?>
$(function(){
	$( "#published_at" ).datepicker({
			showButtonPanel: true,
			showOn: "button",
			buttonImage: "/img/calendar.gif",
	});
	$('#tags').tagsInput({
		'width':'700px',
		autocomplete_url: '/admin/tagautocomplete'
	});
});
<?php 
$this->headScript()->captureEnd();
$this->headStyle()->captureStart() 
?>
#addform {
 
    width: 98%;
    padding: 20px;
    background: #f0f0f0;
    overflow:auto;
 
    /* Border style */
    border: 1px solid #cccccc;
    -moz-border-radius: 7px;
    -webkit-border-radius: 7px;
    border-radius: 7px; 
 
    /* Border Shadow */
    -moz-box-shadow: 2px 2px 2px #cccccc;
    -webkit-box-shadow: 2px 2px 2px #cccccc;
    box-shadow: 2px 2px 2px #cccccc;
}
.field {
	margin-bottom: 10px;
	}
.input{
    font-family: Arial, Verdana;
    font-size: 15px;
    padding: 5px;
    border: 1px solid #b9bdc1;
    width: 700px;
    color: #797979;
    }
    
.hint{
    display:none;
    }
    
.field:hover .hint {
    position: absolute;
    display: block;
    margin: -30px 0 0 455px;
    color: #FFFFFF;
    padding: 7px 10px;
    background: rgba(0, 0, 0, 0.6);
 
    -moz-border-radius: 7px;
    -webkit-border-radius: 7px;
    border-radius: 7px;
    }
    
.button{
    float: right;
    margin:10px 55px 10px 0;
    font-weight: bold;
    line-height: 1;
    padding: 6px 10px;
    cursor:pointer;
    color: #fff;
 
    text-align: center;
    text-shadow: 0 -1px 1px #64799e;
 
    /* Background gradient */
    background: #a5b8da;
    background: -moz-linear-gradient
       (top, #a5b8da 0%, #7089b3 100%);
    background: -webkit-gradient
       (linear, 0% 0%, 0% 100%,
       from(#a5b8da), to(#7089b3));
 
    /* Border style */
    border: 1px solid #5c6f91;
    -moz-border-radius: 10px;
    -webkit-border-radius: 10px;
    border-radius: 10px;
 
    /* Box shadow */
    -moz-box-shadow: inset 0 1px 0 0 #aec3e5;
    -webkit-box-shadow: inset 0 1px 0 0 #aec3e5;
    box-shadow: inset 0 1px 0 0 #aec3e5;
 
    }
    
.errors {
	background-color: pink;
	border: 2px solid red;
	width: 100%;
	padding: 10px;
	margin-bottom: 10px;
	}
<?php $this->headStyle()->captureEnd(); ?>


<?php if(isset($this->errors)): ?>
<div class="errors">
	There was an error creating the tutorial:
	<ul>
	<?php foreach($this->errors as $error): ?>
		<li><?=$error?></li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<form id="addform" class="rounded" method="post" action="">
	<h3>Add A Tutorial</h3>
	 
	<div class="field">
	    <label for="name">Title:</label>
	    <input type="text" class="input" name="title" id="title" value="<?=$this->form["title"]?>" />
	    <p class="hint">Enter a title for the tutorial</p>
	</div>
	 
	 <div class="field">
	    <label for="url">Tutorial URL:</label>
	    <input type="text" class="input" name="url" id="url" value="<?=$this->form["url"]?>" />
	    <p class="hint">Enter the URL of the author</p>
	</div> 
	 
	<div class="field">
		<label for="category">Category:</label>
		<select name="category" id="category" class="input" >
			<option value="">Choose a category</option>
			<?php foreach(Category::all() as $category): ?>
			<option value="<?=$category->id?>" <?php if($this->form["category"]==$category->id):?>selected="selected"<?php endif; ?>><?=$category->name?></option>
			<?php endforeach; ?>
		</select>
		 <p class="hint">Choose a category!</p>
	</div>
	 
	 
	 <div class="field">
	    <label for="tags">Tags:</label>
	    <input type="text" class="input" name="tags" id="tags" value="<?=$this->form["tags"]?>" />
	    <p class="hint">Add some tags, comma-delimited list</p>
	</div> 
	 
	 <div class="field">
	    <label for="published_at">Date Published:</label>
	    <input type="text" class="input" name="published_at" id="published_at" value="<?=$this->form["published_at"]?>" style="width: 660px; margin-right: 5px;" />
	    <p class="hint">When was the article published?</p>
	</div> 
	 
	 <div class="field">
	    <label for="description">Description: (optional)</label>
	    <textarea class="input textarea" name="description" id="description"><?=$this->form["description"]?></textarea>
	    <p class="hint">Write a short description.</p>
	</div>
	 
	<hr />

	<div class="field">
	    <label for="author">Author name:</label>
	    <input type="text" class="input" name="author" id="author" value="<?=$this->form["author"]?>" />
	    <p class="hint">Enter the name of the author</p>
	</div>
	 
	 <div class="field">
	    <label for="author">Author URL:</label>
	    <input type="text" class="input" name="author_url" id="author_url" value="<?=$this->form["author_url"]?>" />
	    <p class="hint">Enter the URL of the author</p>
	</div>

	 
	<input type="submit" name="Submit"  class="button" value="Submit" />
</form>